trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/Authentication/ClientCredentialFlow/DotNet'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/Authentication/ClientCredentialFlow/DotNet'

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - master
    always: true

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/Authentication/ClientCredentialFlow/DotNet'
  - name: CredFile
    value: appsettings.json
  - name: CredFileLibrary
    value: product-readiness.auth_cc_dotnet.json
  - name: projectName
    value: Auth_CC_DotNet

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          imageName: ubuntu-latest
        windows:
          imageName: windows-latest
    pool:
      vmImage: $(imageName)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          filePath: $(projPath)/ClientCredentialFlow

      - script: |
          echo Clean
          call dotnet clean
          echo Build
          call dotnet build
          echo Delete Old Test Results
          del TestResults\*.trx
          echo Test
          call dotnet test --logger trx
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Run tests'

      - task: PublishTestResults@2
        inputs:
          testResultsFormat: VSTest
          testResultsFiles: '*.trx'
          searchFolder: $(Build.SourcesDirectory)$(testPath)/TestResults
        condition: always()
        displayName: 'Publish test results'

  - template: '/miscellaneous/build_templates/analysis.yml'
    parameters:
      language: dotnet
